// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: Database/databaseoperations.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Database_databaseoperations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_Database_databaseoperations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginCredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCredRequest) Reset() {
	*x = LoginCredRequest{}
	mi := &file_Database_databaseoperations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCredRequest) ProtoMessage() {}

func (x *LoginCredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCredRequest.ProtoReflect.Descriptor instead.
func (*LoginCredRequest) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{2}
}

func (x *LoginCredRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginCredRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginCred struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCred) Reset() {
	*x = LoginCred{}
	mi := &file_Database_databaseoperations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCred) ProtoMessage() {}

func (x *LoginCred) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCred.ProtoReflect.Descriptor instead.
func (*LoginCred) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{3}
}

func (x *LoginCred) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginCred) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginCredList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*LoginCred           `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginCredList) Reset() {
	*x = LoginCredList{}
	mi := &file_Database_databaseoperations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCredList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCredList) ProtoMessage() {}

func (x *LoginCredList) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCredList.ProtoReflect.Descriptor instead.
func (*LoginCredList) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{4}
}

func (x *LoginCredList) GetCredentials() []*LoginCred {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_Database_databaseoperations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{5}
}

func (x *UserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cust_Id       int32                  `protobuf:"varint,1,opt,name=Cust_Id,json=CustId,proto3" json:"Cust_Id,omitempty"`
	Cust_Name     string                 `protobuf:"bytes,2,opt,name=Cust_Name,json=CustName,proto3" json:"Cust_Name,omitempty"`
	Cust_Email    string                 `protobuf:"bytes,3,opt,name=Cust_Email,json=CustEmail,proto3" json:"Cust_Email,omitempty"`
	Cust_PNum     string                 `protobuf:"bytes,4,opt,name=Cust_PNum,json=CustPNum,proto3" json:"Cust_PNum,omitempty"`
	Cust_Bal      float32                `protobuf:"fixed32,5,opt,name=Cust_Bal,json=CustBal,proto3" json:"Cust_Bal,omitempty"`
	UserName      string                 `protobuf:"bytes,6,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_Database_databaseoperations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{6}
}

func (x *UserDetails) GetCust_Id() int32 {
	if x != nil {
		return x.Cust_Id
	}
	return 0
}

func (x *UserDetails) GetCust_Name() string {
	if x != nil {
		return x.Cust_Name
	}
	return ""
}

func (x *UserDetails) GetCust_Email() string {
	if x != nil {
		return x.Cust_Email
	}
	return ""
}

func (x *UserDetails) GetCust_PNum() string {
	if x != nil {
		return x.Cust_PNum
	}
	return ""
}

func (x *UserDetails) GetCust_Bal() float32 {
	if x != nil {
		return x.Cust_Bal
	}
	return 0
}

func (x *UserDetails) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UserDetailsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserDetails         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailsList) Reset() {
	*x = UserDetailsList{}
	mi := &file_Database_databaseoperations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailsList) ProtoMessage() {}

func (x *UserDetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_Database_databaseoperations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailsList.ProtoReflect.Descriptor instead.
func (*UserDetailsList) Descriptor() ([]byte, []int) {
	return file_Database_databaseoperations_proto_rawDescGZIP(), []int{7}
}

func (x *UserDetailsList) GetUsers() []*UserDetails {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_Database_databaseoperations_proto protoreflect.FileDescriptor

var file_Database_databaseoperations_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x43,
	0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x46, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x43, 0x75, 0x73, 0x74, 0x5f, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x75, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x43, 0x75, 0x73, 0x74, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x43, 0x75, 0x73, 0x74, 0x5f, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x75, 0x73, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x43,
	0x75, 0x73, 0x74, 0x5f, 0x50, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x75, 0x73, 0x74, 0x50, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74,
	0x5f, 0x42, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x43, 0x75, 0x73, 0x74,
	0x42, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x3e, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32,
	0xd2, 0x02, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x12, 0x0f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x72, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x44,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_Database_databaseoperations_proto_rawDescOnce sync.Once
	file_Database_databaseoperations_proto_rawDescData []byte
)

func file_Database_databaseoperations_proto_rawDescGZIP() []byte {
	file_Database_databaseoperations_proto_rawDescOnce.Do(func() {
		file_Database_databaseoperations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Database_databaseoperations_proto_rawDesc), len(file_Database_databaseoperations_proto_rawDesc)))
	})
	return file_Database_databaseoperations_proto_rawDescData
}

var file_Database_databaseoperations_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_Database_databaseoperations_proto_goTypes = []any{
	(*Empty)(nil),            // 0: Database.Empty
	(*LoginRequest)(nil),     // 1: Database.LoginRequest
	(*LoginCredRequest)(nil), // 2: Database.LoginCredRequest
	(*LoginCred)(nil),        // 3: Database.LoginCred
	(*LoginCredList)(nil),    // 4: Database.LoginCredList
	(*UserRequest)(nil),      // 5: Database.UserRequest
	(*UserDetails)(nil),      // 6: Database.UserDetails
	(*UserDetailsList)(nil),  // 7: Database.UserDetailsList
}
var file_Database_databaseoperations_proto_depIdxs = []int32{
	3, // 0: Database.LoginCredList.credentials:type_name -> Database.LoginCred
	6, // 1: Database.UserDetailsList.users:type_name -> Database.UserDetails
	1, // 2: Database.DatabaseService.CheckLoginCredentials:input_type -> Database.LoginRequest
	2, // 3: Database.DatabaseService.LoadLoginCred:input_type -> Database.LoginCredRequest
	0, // 4: Database.DatabaseService.GetAllLoginCred:input_type -> Database.Empty
	0, // 5: Database.DatabaseService.GetAllUserData:input_type -> Database.Empty
	5, // 6: Database.DatabaseService.GetUserByUserDetails:input_type -> Database.UserRequest
	0, // 7: Database.DatabaseService.CheckLoginCredentials:output_type -> Database.Empty
	0, // 8: Database.DatabaseService.LoadLoginCred:output_type -> Database.Empty
	4, // 9: Database.DatabaseService.GetAllLoginCred:output_type -> Database.LoginCredList
	7, // 10: Database.DatabaseService.GetAllUserData:output_type -> Database.UserDetailsList
	6, // 11: Database.DatabaseService.GetUserByUserDetails:output_type -> Database.UserDetails
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Database_databaseoperations_proto_init() }
func file_Database_databaseoperations_proto_init() {
	if File_Database_databaseoperations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Database_databaseoperations_proto_rawDesc), len(file_Database_databaseoperations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Database_databaseoperations_proto_goTypes,
		DependencyIndexes: file_Database_databaseoperations_proto_depIdxs,
		MessageInfos:      file_Database_databaseoperations_proto_msgTypes,
	}.Build()
	File_Database_databaseoperations_proto = out.File
	file_Database_databaseoperations_proto_goTypes = nil
	file_Database_databaseoperations_proto_depIdxs = nil
}
